ktor:
    application:
        modules:
            - com.ApplicationKt.module
    deployment:
        host: "0.0.0.0"
        port: 8000
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "32#!@3sdja@#!jd23#GFD321dsadasDSA"

db:
  mongo:
    user: "admin"
    password: "password"
    name: "Chirp"
